### ISSUE TITLE
USBD01

### ISSUE THREAD

**Issue by GoncaloAmaral1230796** [JoaoDiasLeite/lei-24-s1-2nb-g321#24]
As a Product Owner, I want a data dictionary/glossary to be created, so that it's easier to communicate with the client.

Acceptance Criteria:
The Label should cover all terms related to the project and its theme, which is production management in an industrial facility.
Subtasks:
– Find and discuss with the client the meaning of some words in this project.
“Done” when all the important terms in the project have a clear meaning.

**Comment by joaobarrosodev** [comment]
O título não está correto, é melhor colocarmos os nomes todos corretos seguindo a seguinte nomenclatura "[STORIE] - [Titulo]" ou seja este ficaria "USBD01 - As a Product Owner, I want a data dictionary/glossary to be created, so that it's easier to communicate with the client"
